---
abstract: ~
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cath-Tools-Seqscan
no_index:
  directory:
    - inc
    - t
requires:
  Log::Dispatch: 0
  Moo: 0
  MooX::Options: 0
  Path::Class: 0
  REST::Client: 0
  URI: 0
version: undef
